/**
 * Define a set of template paths to pre-load
 * Pre-loaded templates are compiled and cached for fast access when rendering
 * @return {Promise}
 */
export const PreloadTemplates = async function() {

  const path = `systems/knight/templates`;

  // Define template paths to load
  const templatePaths = [
    `${path}/items/armures/capacites/personnalise.html`,
    `${path}/items/armures/capacites/ascension.html`,
    `${path}/items/armures/capacites/borealis.html`,
    `${path}/items/armures/capacites/shrine.html`,
    `${path}/items/armures/capacites/cea.html`,
    `${path}/items/armures/capacites/changeling.html`,
    `${path}/items/armures/capacites/companions.html`,
    `${path}/items/armures/capacites/discord.html`,
    `${path}/items/armures/capacites/falcon.html`,
    `${path}/items/armures/capacites/forward.html`,
    `${path}/items/armures/capacites/record.html`,
    `${path}/items/armures/capacites/rewind.html`,
    `${path}/items/armures/capacites/goliath.html`,
    `${path}/items/armures/capacites/ghost.html`,
    `${path}/items/armures/capacites/illumination.html`,
    `${path}/items/armures/capacites/longbow.html`,
    `${path}/items/armures/capacites/mechanic.html`,
    `${path}/items/armures/capacites/morph.html`,
    `${path}/items/armures/capacites/nanoc.html`,
    `${path}/items/armures/capacites/oriflamme.html`,
    `${path}/items/armures/capacites/puppet.html`,
    `${path}/items/armures/capacites/rage.html`,
    `${path}/items/armures/capacites/sarcophage.html`,
    `${path}/items/armures/capacites/totem.html`,
    `${path}/items/armures/capacites/type.html`,
    `${path}/items/armures/capacites/vision.html`,
    `${path}/items/armures/capacites/warlord.html`,
    `${path}/items/armures/capacites/watchtower.html`,
    `${path}/items/armures/capacites/windtalker.html`,
    `${path}/items/armures/capacites/zen.html`,
    `${path}/items/armures/special/personnalise.html`,
    `${path}/items/armures/special/apeiron.html`,
    `${path}/items/armures/special/contrecoups.html`,
    `${path}/items/armures/special/impregnation.html`,
    `${path}/items/armures/special/lenteetlourde.html`,
    `${path}/items/armures/special/plusespoir.html`,
    `${path}/items/armures/special/porteurlumiere.html`,
    `${path}/items/armures/special/recolteflux.html`,
    `${path}/items/armures/special/energiedeficiente.html`,
    `${path}/items/armures/evolutions/borealis.html`,
    `${path}/items/armures/evolutions/oriflamme.html`,
    `${path}/items/armures/evolutions/changeling.html`,
    `${path}/items/armures/evolutions/goliath.html`,
    `${path}/items/armures/evolutions/falcon.html`,
    `${path}/items/armures/evolutions/ghost.html`,
    `${path}/items/armures/evolutions/longbow.html`,
    `${path}/items/armures/evolutions/mechanic.html`,
    `${path}/items/armures/evolutions/nanoc.html`,
    `${path}/items/armures/evolutions/shrine.html`,
    `${path}/items/armures/evolutions/type.html`,
    `${path}/items/armures/evolutions/vision.html`,
    `${path}/items/armures/evolutions/warlord.html`,
    `${path}/items/armures/evolutions/watchtower.html`,
    `${path}/items/armures/evolutions/cea.html`,
    `${path}/items/armures/evolutions/discord.html`,
    `${path}/items/armures/evolutions/puppet.html`,
    `${path}/items/armures/evolutions/windtalker.html`,
    `${path}/items/armures/evolutions/zen.html`,
    `${path}/items/armures/evolutions/morph.html`,
    `${path}/items/armures/evolutions/companions.html`,
    `${path}/items/armures/evolutions/ascension.html`,
    `${path}/items/armures/evolutions/forward.html`,
    `${path}/items/armures/evolutions/record.html`,
    `${path}/items/armures/evolutions/rewind.html`,
    `${path}/items/armures/evolutions/totem.html`,
    `${path}/items/armures/evolutions/illumination.html`,
    `${path}/items/armures/evolutions/rage.html`,
    `${path}/items/armures/evolutions/lenteetlourde.html`,
    `${path}/items/armures/evolutions/plusespoir.html`,
    `${path}/items/armures/evolutions/porteurlumiere.html`,
    `${path}/items/armures/evolutions/impregnation.html`,
    `${path}/items/armures/evolutions/contrecoups.html`,
    `${path}/items/armures/evolutions/apeiron.html`,
    `${path}/items/armures/evolutions/recolteflux.html`,
    `${path}/actors/subtab/historique.html`,
    `${path}/actors/subtab/personnagePNJ.html`,
    `${path}/actors/subtab/aspectsPNJ.html`,
    `${path}/actors/subtab/aspectsExceptionnels.html`,
    `${path}/dialog/ask-sheet.html`,
    `${path}/dialog/parts/compendium-filter.html`,
    `${path}/dialog/parts/wpnOptions.html`,
    `${path}/items/armuresLegende/capacites/personnalise.html`,
    `${path}/items/armuresLegende/capacites/shrine.html`,
    `${path}/items/armuresLegende/capacites/changeling.html`,
    `${path}/items/armuresLegende/capacites/companions.html`,
    `${path}/items/armuresLegende/capacites/discord.html`,
    `${path}/items/armuresLegende/capacites/falcon.html`,
    `${path}/items/armuresLegende/capacites/record.html`,
    `${path}/items/armuresLegende/capacites/rewind.html`,
    `${path}/items/armuresLegende/capacites/goliath.html`,
    `${path}/items/armuresLegende/capacites/ghost.html`,
    `${path}/items/armuresLegende/capacites/mechanic.html`,
    `${path}/items/armuresLegende/capacites/nanoc.html`,
    `${path}/items/armuresLegende/capacites/oriflamme.html`,
    `${path}/items/armuresLegende/capacites/puppet.html`,
    `${path}/items/armuresLegende/capacites/totem.html`,
    `${path}/items/armuresLegende/capacites/type.html`,
    `${path}/items/armuresLegende/capacites/vision.html`,
    `${path}/items/armuresLegende/capacites/warlord.html`,
    `${path}/items/armuresLegende/capacites/windtalker.html`,
    `${path}/items/armuresLegende/special/recolteflux.html`,
    `${path}/actors/mechaarmure/volMarkIV.html`,
    `${path}/actors/mechaarmure/sautMarkIV.html`,
    `${path}/actors/mechaarmure/vagueSoin.html`,
    `${path}/actors/mechaarmure/canonMetatron.html`,
    `${path}/actors/mechaarmure/canonNoe.html`,
    `${path}/actors/mechaarmure/canonMagma.html`,
    `${path}/actors/mechaarmure/lamesCinetiquesGeantes.html`,
    `${path}/actors/mechaarmure/mitrailleusesSurtur.html`,
    `${path}/actors/mechaarmure/tourellesLasersAutomatisees.html`,
    `${path}/actors/mechaarmure/missilesJericho.html`,
    `${path}/actors/mechaarmure/souffleDemoniaque.html`,
    `${path}/actors/mechaarmure/poingsSoniques.html`,
    `${path}/actors/mechaarmure/chocSonique.html`,
    `${path}/actors/mechaarmure/bouclierAmrita.html`,
    `${path}/actors/mechaarmure/offering.html`,
    `${path}/actors/mechaarmure/curse.html`,
    `${path}/actors/mechaarmure/podMiracle.html`,
    `${path}/actors/mechaarmure/podInvulnerabilite.html`,
    `${path}/actors/mechaarmure/dronesEvacuation.html`,
    `${path}/actors/mechaarmure/dronesAirain.html`,
    `${path}/actors/mechaarmure/moduleEmblem.html`,
    `${path}/actors/mechaarmure/moduleInferno.html`,
    `${path}/actors/mechaarmure/moduleWraith.html`,
    `${path}/actors/mechaarmure/stationDefenseAutomatise.html`,
    `${path}/actors/mechaarmure/modeSiegeTower.html`,
    `${path}/actors/mechaarmure/nanoBrume.html`,
    `${path}/items/capacitesUltimes/passives/base.html`,
    `${path}/items/capacitesUltimes/passives/ascension.html`,
    `${path}/items/capacitesUltimes/passives/cea.html`,
    `${path}/items/capacitesUltimes/passives/changeling.html`,
    `${path}/items/capacitesUltimes/passives/companions.html`,
    `${path}/items/capacitesUltimes/passives/contrecoups.html`,
    `${path}/items/capacitesUltimes/passives/ghost.html`,
    `${path}/items/capacitesUltimes/passives/goliath.html`,
    `${path}/items/capacitesUltimes/passives/mechanic.html`,
    `${path}/items/capacitesUltimes/passives/morph.html`,
    `${path}/items/capacitesUltimes/passives/oriflamme.html`,
    `${path}/items/capacitesUltimes/passives/rage.html`,
    `${path}/items/capacitesUltimes/passives/recolteflux.html`,
    `${path}/items/capacitesUltimes/passives/type.html`,
    `${path}/items/capacitesUltimes/passives/vision.html`,
    `${path}/items/capacitesUltimes/passives/warlord.html`,
    `${path}/items/capacitesUltimes/actives/base.html`,
    `${path}/parts/damage/dice.hbs`,
    `${path}/parts/damage/header.hbs`,
    `${path}/parts/damage/variable.hbs`,
  ];

  const commonPartials = {
    "knight.armes": `${path}/actors/parts/common/sections/armes.hbs`,
    "knight.effets": `${path}/common/parts/sections/effets.hbs`,
    "knight.itemButtons": `${path}/actors/parts/common/itemButtons.hbs`,
  }

  const humanPartials = {
    "knight.cyberware": `${path}/actors/parts/human/sections/cyberware.hbs`,
    "knight.longbow": `${path}/actors/parts/human/sections/longbow.hbs`,
    "knight.grenades": `${path}/actors/parts/human/sections/grenades.hbs`,
    "knight.nods": `${path}/actors/parts/human/sections/nods.hbs`,
    "knight.modules": `${path}/actors/parts/human/sections/modules.hbs`,
  };

  const actorCapacitesPartials = {
    'knight.actor.capacites.ascension':`${path}/actors/parts/human/sections/capacites/ascension.hbs`,
    'knight.actor.capacites.sarcophage':`${path}/actors/parts/human/sections/capacites/sarcophage.hbs`,
    'knight.actor.capacites.shrine':`${path}/actors/parts/human/sections/capacites/shrine.hbs`,
    'knight.actor.capacites.personnalise':`${path}/actors/parts/human/sections/capacites/personnalise.hbs`,
    'knight.actor.capacites.borealis':`${path}/actors/parts/human/sections/capacites/borealis.hbs`,
    'knight.actor.capacites.changeling':`${path}/actors/parts/human/sections/capacites/changeling.hbs`,
    'knight.actor.capacites.companions':`${path}/actors/parts/human/sections/capacites/companions.hbs`,
    'knight.actor.capacites.cea':`${path}/actors/parts/human/sections/capacites/cea.hbs`,
    'knight.actor.capacites.discord':`${path}/actors/parts/human/sections/capacites/discord.hbs`,
    'knight.actor.capacites.falcon':`${path}/actors/parts/human/sections/capacites/falcon.hbs`,
    'knight.actor.capacites.forward':`${path}/actors/parts/human/sections/capacites/forward.hbs`,
    'knight.actor.capacites.ghost':`${path}/actors/parts/human/sections/capacites/ghost.hbs`,
    'knight.actor.capacites.goliath':`${path}/actors/parts/human/sections/capacites/goliath.hbs`,
    'knight.actor.capacites.illumination':`${path}/actors/parts/human/sections/capacites/illumination.hbs`,
    'knight.actor.capacites.longbow':`${path}/actors/parts/human/sections/capacites/longbow.hbs`,
    'knight.actor.capacites.mechanic':`${path}/actors/parts/human/sections/capacites/mechanic.hbs`,
    'knight.actor.capacites.morph':`${path}/actors/parts/human/sections/capacites/morph.hbs`,
    'knight.actor.capacites.oriflamme':`${path}/actors/parts/human/sections/capacites/oriflamme.hbs`,
    'knight.actor.capacites.puppet':`${path}/actors/parts/human/sections/capacites/puppet.hbs`,
    'knight.actor.capacites.rage':`${path}/actors/parts/human/sections/capacites/rage.hbs`,
    'knight.actor.capacites.record':`${path}/actors/parts/human/sections/capacites/record.hbs`,
    'knight.actor.capacites.rewind':`${path}/actors/parts/human/sections/capacites/rewind.hbs`,
    'knight.actor.capacites.totem':`${path}/actors/parts/human/sections/capacites/totem.hbs`,
    'knight.actor.capacites.warlord':`${path}/actors/parts/human/sections/capacites/warlord.hbs`,
    'knight.actor.capacites.watchtower':`${path}/actors/parts/human/sections/capacites/watchtower.hbs`,
    'knight.actor.capacites.windtalker':`${path}/actors/parts/human/sections/capacites/windtalker.hbs`,
    'knight.actor.capacites.zen':`${path}/actors/parts/human/sections/capacites/zen.hbs`,
    'knight.actor.capacites.nanoc':`${path}/actors/parts/human/sections/capacites/nanoc.hbs`,
    'knight.actor.capacites.type':`${path}/actors/parts/human/sections/capacites/type.hbs`,
    'knight.actor.capacites.vision':`${path}/actors/parts/human/sections/capacites/vision.hbs`,
  };

  const actorCapacitesLegendsPartials = {
    'knight.actor.capacitesLegends.personnalise':`${path}/actors/parts/human/sections/capacitesLegende/personnalise.hbs`,
    'knight.actor.capacitesLegends.shrine':`${path}/actors/parts/human/sections/capacitesLegende/shrine.hbs`,
    'knight.actor.capacitesLegends.changeling':`${path}/actors/parts/human/sections/capacitesLegende/changeling.hbs`,
    'knight.actor.capacitesLegends.companions':`${path}/actors/parts/human/sections/capacitesLegende/companions.hbs`,
    'knight.actor.capacitesLegends.discord':`${path}/actors/parts/human/sections/capacitesLegende/discord.hbs`,
    'knight.actor.capacitesLegends.falcon':`${path}/actors/parts/human/sections/capacitesLegende/falcon.hbs`,
    'knight.actor.capacitesLegends.record':`${path}/actors/parts/human/sections/capacitesLegende/record.hbs`,
    'knight.actor.capacitesLegends.rewind':`${path}/actors/parts/human/sections/capacitesLegende/rewind.hbs`,
    'knight.actor.capacitesLegends.goliath':`${path}/actors/parts/human/sections/capacitesLegende/goliath.hbs`,
    'knight.actor.capacitesLegends.ghost':`${path}/actors/parts/human/sections/capacitesLegende/ghost.hbs`,
    'knight.actor.capacitesLegends.mechanic':`${path}/actors/parts/human/sections/capacitesLegende/mechanic.hbs`,
    'knight.actor.capacitesLegends.nanoc':`${path}/actors/parts/human/sections/capacitesLegende/nanoc.hbs`,
    'knight.actor.capacitesLegends.oriflamme':`${path}/actors/parts/human/sections/capacitesLegende/oriflamme.hbs`,
    'knight.actor.capacitesLegends.puppet':`${path}/actors/parts/human/sections/capacitesLegende/puppet.hbs`,
    'knight.actor.capacitesLegends.totem':`${path}/actors/parts/human/sections/capacitesLegende/totem.hbs`,
    'knight.actor.capacitesLegends.type':`${path}/actors/parts/human/sections/capacitesLegende/type.hbs`,
    'knight.actor.capacitesLegends.vision':`${path}/actors/parts/human/sections/capacitesLegende/vision.hbs`,
    'knight.actor.capacitesLegends.warlord':`${path}/actors/parts/human/sections/capacitesLegende/warlord.hbs`,
    'knight.actor.capacitesLegends.windtalker':`${path}/actors/parts/human/sections/capacitesLegende/windtalker.hbs`,
  };

  const actorSpecialPartials = {
    'knight.actor.special.apeiron':`${path}/actors/parts/human/sections/special/apeiron.hbs`,
    'knight.actor.special.contrecoups':`${path}/actors/parts/human/sections/special/contrecoups.hbs`,
    'knight.actor.special.impregnation':`${path}/actors/parts/human/sections/special/impregnation.hbs`,
    'knight.actor.special.lenteetlourde':`${path}/actors/parts/human/sections/special/lenteetlourde.hbs`,
    'knight.actor.special.personnalise':`${path}/actors/parts/human/sections/special/personnalise.hbs`,
    'knight.actor.special.plusespoir':`${path}/actors/parts/human/sections/special/plusespoir.hbs`,
    'knight.actor.special.porteurlumiere':`${path}/actors/parts/human/sections/special/porteurlumiere.hbs`,
    'knight.actor.special.recolteflux':`${path}/actors/parts/human/sections/special/recolteflux.hbs`,
    'knight.actor.special.energiedeficiente':`${path}/actors/parts/human/sections/special/energiedeficiente.hbs`,
  };

  const actorSpecialLegendsPartials = {
    'knight.actor.specialLegends.recolteflux':`${path}/actors/parts/human/sections/specialLegende/recolteflux.hbs`,
  }

  const pcPartials = {
    "knight.distinctions": `${path}/actors/parts/pc/sections/distinctions.hbs`,
  };

  const creaturePartials = {};

  // Précharger
  return foundry.applications.handlebars.loadTemplates({
    ...commonPartials,
    ...humanPartials,
    ...pcPartials,
    ...creaturePartials,
    ...actorCapacitesPartials,
    ...actorCapacitesLegendsPartials,
    ...actorSpecialPartials,
    ...actorSpecialLegendsPartials,
  });
};